services:
  jupyter:
    image: cryptotrendpredict:latest
    container_name: jupyter-crypto
    runtime: nvidia 
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - JUPYTER_ENABLE_LAB=yes
      - TF_CPP_MIN_LOG_LEVEL=2
      - TF_ENABLE_ONEDNN_OPTS=0
    volumes:
      - ./:/home/jovyan/files
    networks:
      bitcoin_network:
        ipv4_address: 172.29.0.3
    ports:
      - "8888:8888"
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''

networks:
  bitcoin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
