services:
  jupyter:
    image: cryptotrendpredict:latest
    container_name: jupyter-crypto
    env_file:
      - .env
    volumes:
      - ./:/home/jovyan/files
    networks:
      bitcoin_network:
        ipv4_address: 172.29.0.3
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''

networks:
  bitcoin_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16
